### ISSUE TITLE
Describe portfolio function, members, what they do and how, from getting insights fro strategy, govern entities, stakeholders etc. In other words describe how you met inputs and request coming from the figure below, describe figure below.

### ISSUE THREAD

**Issue by MrCarrera** [digdir/baksia#712] opened 2024-08-22 08:12 UTC
Describe this flow. 

![Image](https://github.com/user-attachments/assets/50e95759-ed9c-4cbd-a164-a57d19f491b6)

**Comment by altinnadmin** [comment] 2024-10-01 08:10
@fsveinsb Duplicate of #811, closing this.

**Closed by altinnadmin** 2024-10-01 08:10 UTC
